-- Initialize PostGIS extension
CREATE EXTENSION IF NOT EXISTS postgis;

-- Grant necessary permissions
GRANT ALL PRIVILEGES ON SCHEMA public TO pickleup;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO pickleup;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO pickleup;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO pickleup;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO pickleup;
